# Setup
title:               The Return of the Rosy Reign
tagline:             'The Most Important Warning You''ll Ever Read'
description:         ''
domain:              therosyreign.org    
url:                 http://www.therosyreign.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dr. Alexis "Alex" Veritas
  url:               http://www.therosyreign.org

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
